name: Module Shortcut

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  module-shortcut:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          repository: 'EvntBoard/module-shortcut'
          path: 'module-shortcut'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - id: get_version
        uses: battila7/get-version-action@v2

      ## IOHOOK PART

      - name: Setup Linux Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common libx11-dev libxtst-dev libxt-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libxcb-xkb-dev libxkbfile-dev libxinerama-dev

## --branch=v0.9.3
      - name: Rebuild iohook
        run: |
          git clone https://github.com/wilix-team/iohook.git iohook
          cd iohook
          npm i --ignore-scripts
          npm run build --msvs_version=2019

      ## IOHOOK PART

      - name: Build Linux x64
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd module-shortcut
          yarn
          yarn prebuild:x64
          yarn build:x64:linux
          cd ../
          mkdir -p module-shortcut/build/linux-x64/module/node_modules/iohook/builds/node-v72-linux-x64/build/Release
          cp iohook/build/Release/iohook.node module-shortcut/build/linux-x64/module/node_modules/iohook/builds/node-v72-linux-x64/build/Release/iohook.node
          cp iohook/build/Release/uiohook.so module-shortcut/build/linux-x64/module/node_modules/iohook/builds/node-v72-linux-x64/build/Release/uiohook.so

      - name: Build Windows x64
        if: startsWith(matrix.os, 'windows')
        run: |
          cd module-shortcut
          yarn
          yarn prebuild:x64
          yarn build:x64:win
          cd ../
          mkdir -p module-shortcut/build/win-x64/module/node_modules/iohook/builds/node-v72-win32-x64/build/Release
          copy iohook/build/Release/iohook.node module-shortcut/build/win-x64/module/node_modules/iohook/builds/node-v72-win32-x64/build/Release/iohook.node
          copy iohook/build/Release/uiohook.dll module-shortcut/build/win-x64/module/node_modules/iohook/builds/node-v72-win32-x64/build/Release/uiohook.dll

      - name: Build MacOS x64
        if: startsWith(matrix.os, 'macos')
        run: |
          cd module-shortcut
          yarn
          yarn prebuild:x64
          yarn build:x64:macos
          cd ../
          mkdir -p module-shortcut/build/macos-x64/module/node_modules/iohook/builds/node-v72-darwin-x64/build/Release
          cp iohook/build/Release/iohook.node module-shortcut/build/macos-x64/module/node_modules/iohook/builds/node-v72-darwin-x64/build/Release/iohook.node
          cp iohook/build/Release/uiohook.dylib module-shortcut/build/macos-x64/module/node_modules/iohook/builds/node-v72-darwin-x64/build/Release/uiohook.dylib

      - name: Copy metadata.json & config.json & generate REPO + VERSION
        run: |
          cp ./metadata.json ./dist/metadata.json
          cp ./defaultConfig.json ./dist/config.json
          echo ${{ github.repository }} > ./dist/REPO.TXT
          echo ${{ steps.get_version.outputs.version }} > ./dist/VERSION.TXT

      - name: Pack Linux x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'ubuntu')
        run: |
          cd module-shortcut/build/linux-x64
          npx bestzip ../../../module-shortcut-linux-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Pack Win x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'windows')
        run: |
          cd module-shortcut/build/win-x64
          npx bestzip ../../../module-shortcut-win-x64-${{ steps.get_version.outputs.version }}.zip .

      - name: Pack Macos x64
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'macos')
        run: |
          cd module-shortcut/build/macos-x64
          npx bestzip ../../../module-shortcut-macos-x64--${{ steps.get_version.outputs.version }}.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            *.zip